	<h1>Ajout d'une catégorie</h1>
	<!-- sipas d'attribut action, par défaut, la soumission du formulaire fait un rechargement de la même page-->
	<form method="post">
		<p>
			<label for='nom'>Nom de la catégorie</label>
			<input type="text" name="nom" id="nom">
		</p>
		<p>
			<label for='is_dish'>Plat principal ?</label>
			<input type="checkbox" name="is_dish" id="is_dish">
		</p>
		<p>
			<label for='description'>Description</label>
			<input type="textarea" name="description"/>
		</p>
		
		<button type="submit">Créer la catégorie</button>
	</form>