<main>
	
	<h3>Ajouter un plat</h3>
    
	<form method="post" enctype="multipart/form-data"> <!--action="article.phtml-->
	    <p>
		    <label for='category'>Catégorie</label>
			<select name="category" id="category">
			    <option value="">--Please choose an option--</option>
			    <?php foreach($categories as $categorie): ?>
                <option value="<?= $categorie['id'] ?>"><?= htmlspecialchars($categorie['name']) ?></option>
                <?php endforeach; ?>
            </select>
            </p>
		<p>
		    <label for='name'>Nom du plat</label>
		    <input type="text" name="name" id="name"/>
		</p>
		<p>
			<label for="img">Image</label>
			<input type="file" name="img" id="img"/>
		</p>
		<p>	
			<label for="alt">Alt</label>
			<input type="text" name="alt" id="alt"/>
		</p>

			<button type="submit">Enregistrer</button>
	</form>
	
</main>