	<h1>Ajout d'un slider</h1>
	<form method="post" enctype="multipart/form-data">
		<p>
			<label for='alt'>ALT</label>
			<input type="text" name="alt" id="alt">
		</p>
		<p>
			<label for='published'>Published ?</label>
			<input type="checkbox" name="published" id="published">
		</p>
		<p>
			<label for='poids'>Poids</label>
			<input type="number" name="poids" id="poids"/>
		</p>
		<p>
			<label for='image'>Image</label>
			<input type="file" name="image" id="image">
		</p>
		<button type="submit">Ajouter le slider</button>
	</form>