 <section>
 <h2>Gestion des catégories de plat</h2>
    
        <button><a href="index.php?page=createCategory">Ajouter une catégorie de plat</a></button>
    
    
        <table>
            
            <tr>
                <th>ID</th>
                <th>Catégorie</th>
                <th>Plat principal</th>
                <th>Description</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($categories as $category): ?>
            <tr>
                <td><?= $category['id'] ?></td>
                <td><?= $category['name'] ?></td>
                <td><?= $category['is_dish'] ?></td>
                <td><?= $category['description'] ?></td>
                <td><button><a href="index.php?page=modifCategory&id=<?=$category['id']?>"><i class="fas fa-pen-nib"></i></a></a></button></td>
                <td><button class="confirmButton" data-url="<?= "index.php?page=deleteCategory&id=".$category['id'] ?>"><a><i class="fas fa-trash-alt"></i></a></button></td>
            </tr>
            <?php endforeach; ?>
        </table>
    
    </section>


</main>
    <script src="js/main.js"></script>
