<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Freshly Restaurant, your new favourite restaurant !">
	<title>Freshly Restaurant - Home</title>
	<link rel="icon" href="favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="css/slick.css">
	<link rel="stylesheet" href="css/slick-theme.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="css/style.css">
</head>

<body>
	<header>
		<div class="container">
			<a href="accueil" class="logo">
				<img src="img/logo.png" alt="Logo for Freshly Restaurant">
				<strong>Freshly Restaurant</strong>
			</a>
			<nav>
				<ul>
					<li><a href="accueil" class="active">Home</a></li>
					<li><a href="about">About</a></li>
					<li><a href="menu">Menus</a></li>
					<li><a href="contact">Contact</a></li>
            		    <?php if(isset($_SESSION['user'])): ?>
            		    <li><a href="booking">Réservation</a></li>
            			<!--	<a href="connection">Dashboard</a> -->
            				<li><a href="index.php?page=connexion&action=deco">Deconnexion</a></li>
            				<p>Bonjour <?= $_SESSION['user'] ?></p>
            				<?php else: ?>
            				<li><a href="connexion">Connexion</a></li>
            			<?php endif; ?>
            				<li>
            		    <?php if(isset($_SESSION['admin'])): ?>
            				<a href="dashboard">Dashboard</a>
            				<a href="index.php?page=connexion&action=deco">Deconnexion</a>
            				<p>Bonjour <?= $_SESSION['admin'] ?></p>
            				<?php else: ?>
            				<!--<a href="index.php?page=admin">Admin</a>-->
            			<?php endif; ?>
		            </li>
		            </li>
				</ul>
			</nav>
		</div> <!-- end of .container -->
	</header>
	
		<!-- code principal de la page -->
	<?php include $template ?>
	
	<?php if(!isset($_COOKIE['accept']))
	'<div class="cookie"> 
			<span>🍪 Ce site utilise des cookies et vous donne le contrôle sur ceux que vousouhaitez activer </span>   
			<div>   
				<button class="acceptCookie"> Tout accepter  </button>   
				<button class="rejectCookie">Tout refuser </button>   
			</div>   
		</div>'
		?>
		
		<footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Opening hours</h4>
					<ul>
						<li>Monday: Closed</li>
						<li>Tue-Wed : 9am - 10pm</li>
						<li>Thu-Fri : 9am - 10pm</li>
						<li>Sat-Sun : 5pm - 10pm</li>
					</ul>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>13 Christopher Street<br>
							New York,<br>
							NY 10014-3543</p>
						<p>+01 2000 800 9999</p>
					</address>
				</aside>
				<aside>
					<h4>Social networks</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
			
	<div class="footer">
				<p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p><br>
				<span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants. Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br>
				Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="https://www.cath2nos.com">Catherine Denos</a>.
			</div> <!-- end of .footer -->
		</div> <!-- end of .container -->
	</footer>
	
	</body>
</html>
	
	
	