 <section>
 <h2>Gestion des plats</h2>
    
        <button><a href="index.php?page=createMeal">Ajouter un plat</a></button>
    
        <table>
            <tr>
                <th>ID</th>
                <th>Catégorie</th>
                <th>Nom du plat</th>
                <th>Image src</th>
                <th>Image alt</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach($meals as $meal): ?>
            <tr>
                <td><?= $meal['id'] ?></td>
                <td><?= $meal['categoryName'] ?></td>
                <td><?= $meal['name'] ?></td>
                <td><?= $meal['src'] ?></td>
                <td><?= $meal['alt'] ?></td>
                <td><button><a href="index.php?page=modifyMeal&id=<?=$meal['id']?>"><i class="fas fa-pen-nib"></i></a></a></button></td>
                <td><button class="confirmButton" data-url="<?= "index.php?page=deleteMeal&id=".$meal['id'] ?>"><a><i class="fas fa-trash-alt"></i></a></button></td>
            </tr>
            <?php endforeach; ?>
        </table>
    
    </section>


</main>
    <script src="js/main.js"></script>