<main>

<h3>Modifier un plat</h3>
    
    <form method="post" enctype="multipart/form-data"> 
    	<p>
		    <label for='category'>Catégorie</label>
			<select name="category" id="category">
			    <option value="<?= $meal['id_category'] ?>"> <?= $meal['categoryName'] ?></option>
			    <?php foreach($categories as $categorie): ?>
                <option value="<?= htmlspecialchars($categorie['id']) ?>"><?= htmlspecialchars($categorie['name']) ?></option>
                <?php endforeach; ?>
            </select>
            </p>
		<p>
  
		<p>
			<label for="name">Nom du plat</label>
			<input type="text" name="name" id="name" value="<?= htmlspecialchars($meal['name']) ?>"/>
		</p>
		<p>
			<label for="img">Image</label>
			<input type="file" name="img" id="img"/>
			<input type="hidden" name="imgBdd" id="imgBdd" value="<?= $meal['src'] ?>"/>
			
		</p>
		<p>	
			<label for="alt">Alt</label> 
			<input type="alt" name="alt" id="alt" value="<?= htmlspecialchars($meal['alt']) ?>"/>
		</p>

			<button type="submit">Enregistrer</button>
			 
	</form>
	
</main>