<main>

<h3>Modifier une catégorie</h3>
    
    <form method="post"> 
  
		<p>
			<label for="name">Nom de la catégorie</label>
			<input type="text" name="name" id="name" value="<?= $category['name'] ?>"/>
		</p>
		<p>
			<label for="is_dish">Plat principal ?</label>
			<input type="checkbox" name="is_dish" id="is_dish" <?= ($category['is_dish'] == 1)?"checked":"" ?>>
		</p>
		<p>	
			<label for="description">Description</label> 
			<textarea name="description" id="description"><?= $category['description'] ?></textarea>
		</p>

			<button type="submit">Enregistrer</button>
			 
	</form>
	
</main>