<main>

<h3>Modifier l'Accueil</h3>
    
    <form method="post" enctype="multipart/form-data"> 
  
		<p>
			<label for="name">Nom de la titre</label>
			<input type="text" name="name" id="name" value="<?= $config['name'] ?>"/>
		</p>
		<p>	
			<label for="content">Description</label> 
			<textarea name="content" id="content"><?= $config['content'] ?></textarea>
		</p>
		<p>
			<label for='image'>Image</label>
			<input type="file" name="image" id="image">
			<input type="hidden" name="imageBdd" id="imageBdd" value="<?= $config['src'] ?>"/>
		</p>
		<p>	
			<label for="nameImage">Nom de l'image</label> 
			<textarea name="nameImage" id="nameImage"><?= $config['alt'] ?></textarea>
		</p>

			<button type="submit">Enregistrer</button>
			 
	</form>
	
</main>