<main>
	<form method="post">
		<p>
			<label for='firstName'>Prénom</label>
			<input type="text" name="firstName" id="firstName" value="<?= (isset($_POST['firstName']))? $_POST['firstName']:"" ?>">
		</p>
		<p>
			<label for='lastName'>Nom</label>
			<input type="text" name="lastName" id="lastName" value="<?= (isset($_POST['lastName']))? $_POST['lastName']:"" ?>">
		</p>
		<p>
			<label for='email'>Email</label>
			<input type="email" name="email" id="email">
				<p><?= $this -> message1 ?></p>
		</p>
		<p>
			<label for='phone'>Teléphone</label>
			<input type="tel" name="phone" id="phone" value="<?= (isset($_POST['phone']))? $_POST['phone']:"" ?>">
		</p>
		<p>
			<label for='pw'>Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		
		<button>Créer le compte</button>
	</form>

</main>
</body>

</html>